site_name: Abhijit

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: sk
          name: Slovensky
          build: true
          nav_translations:
            Home: Úvod
            About: O projekte

nav:
  - Home: index.md
  - About: about.md