site_name: Abhijit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Tmavý režim
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Svetlý režim

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: sk
          default: true
          name: Slovensky
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Úvod: Home
            O projekte: About

nav:
  - Úvod: index.md
  - O projekte: about.md